# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
workflows:
  version: 2
  test-php-versions:
    jobs:
      #      - test-8.0:
      #          filters:
      #            branches:
      #              only:
      #                - pre-release
      #                - master
      #      - test-7.4:
      #          filters:
      #            branches:
      #              only:
      #                - pre-release
      #                - master
      - test-7.3:
          filters:
            branches:
              only:
                - pre-release
                - master

jobs:
  test-8.0:
    docker:
      # Specify the version you desire here
      - image: circleci/php:8-cli
    steps:
      - checkout
      - run:
          shell: /bin/bash
          command: |
            cd ~/project  &&
            composer install -n --prefer-dist &&
            /usr/local/bin/php ./vendor/bin/phpunit --testsuite Units &&
            /usr/local/bin/php ./vendor/bin/phpunit --testsuite Feature &&
            /usr/local/bin/php ./vendor/bin/phpunit --testsuite SampleCode &&
            echo done;
  
  test-7.4:
    docker:
      # Specify the version you desire here
      - image: circleci/php:7.4.3-cli
    steps:
      - checkout
      - run:
          shell: /bin/bash
          command: |
            cd ~/project  &&
            composer install -n --prefer-dist &&
            /usr/local/bin/php ./vendor/bin/phpunit --testsuite Units &&
            /usr/local/bin/php ./vendor/bin/phpunit --testsuite Feature &&
            /usr/local/bin/php ./vendor/bin/phpunit --testsuite SampleCode &&
            echo done;
  test-7.3:
    docker:
      # Specify the version you desire here
      - image: php:7.3-cli
    steps:
      - checkout
      - run:
          shell: /bin/bash
          command:
            apt-get update;
            apt-get install -y --no-install-recommends git vim-nox sudo;
      - run:
          shell: /bin/bash
          command: |
            apt-get -y install libzip-dev unzip;
            docker-php-ext-install zip;
            docker-php-ext-enable zip;
      - run:
          shell: /bin/bash
          command: |
            cp -r  project /var/www/project
            chown www-data:www-data /var/www/project -R && chmod g+rwx /var/www/project;
            cd /var/www/project;
            sudo -u www-data php -r "copy('https://getcomposer.org/installer', 'composer-setup.php');" &&
            sudo -u www-data php composer-setup.php
            sudo -u www-data php composer.phar install -n --prefer-dist
      - run:
          shell: /bin/bash
          command: |
            cd ~/project &&
            sudo -u www-data php ./vendor/bin/phpunit --testsuite Units &&
            sudo -u www-data php ./vendor/bin/phpunit --testsuite Feature &&
            sudo -u www-data php ./vendor/bin/phpunit --testsuite SampleCode &&
            echo done;
