# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
workflows:
  version: 2
  test-php-versions:
    jobs:
      - test8.0:
          filters:
            branches:
              only:
                - pre-release
                - master
      - test7.4:
          filters:
            branches:
              only:
                - pre-release
                - master

jobs:
  test-8.0:
    docker:
      # Specify the version you desire here
      - image: circleci/php:8-cli
    steps:
      - checkout
      - run:
          shell: /bin/bash
          command: |
            cd ~/project  &&
            /usr/local/bin/php ./vendor/bin/phpunit --testsuite Units &&
            /usr/local/bin/php ./vendor/bin/phpunit --testsuite Feature &&
            /usr/local/bin/php ./vendor/bin/phpunit --testsuite SampleCode &&
            echo done;
  
  test-7.4:
    docker:
      # Specify the version you desire here
      - image: circleci/php:7.4.3-cli
    steps:
      - checkout
      - run:
          shell: /bin/bash
          command: |
            cd ~/project  &&
            /usr/local/bin/php ./vendor/bin/phpunit --testsuite Units &&
            /usr/local/bin/php ./vendor/bin/phpunit --testsuite Feature &&
            /usr/local/bin/php ./vendor/bin/phpunit --testsuite SampleCode &&
            echo done;
