# PHP CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-php/ for more details
#
version: 2
workflows:
  version: 2
  test_and_installationt:
    jobs:
      - test
jobs:
  test:
    docker:
      # Specify the version you desire here
      - image: circleci/php:7.4.3-cli
    steps:
      - checkout
      - run:
          shell: /bin/bash
          command: |
            # Download and cache dependencies
            ## prepare test for ssh
            sudo apt update
            sudo apt install -y --no-install-recommends openssh-server openssh-client
            sudo /etc/init.d/ssh start
            ## prepare ssh login
            ls ~/.ssh && rm -rf ~/.ssh
            ssh-keygen  -t rsa  -N "" -f ~/.ssh/id_rsa
            cat /home/circleci/.ssh/id_rsa.pub > /home/circleci/.ssh/authorized_keys
            touch ~/.ssh/known_hosts && rm ~/.ssh/known_hosts
            ssh-keyscan -t rsa,dsa localhost  2>/dev/null > ~/.ssh/known_hosts
            ssh localhost date
            ## prepare phpunit
            composer install -n --prefer-dist
            ./vendor/bin/phpunit --testsuite Units
            ./vendor/bin/phpunit --testsuite Feature
            ./vendor/bin/phpunit --testsuite Sample
            ##  test packagist installation
            mkdir /tmp/install-test
            cd /tmp/install-test
            ##
            echo "<?php
               use SystemUtil\Process;
               require_once './vendor/autoload.php';
               $proc = new Process(['echo', 'HelloWorld']);
               $proc->run();"  > run.php
            /usr/local/bin/php run.php

      # run tests with phpunit or codecept
      # - run: ./vendor/bin/codecept build
      # - run: ./vendor/bin/codecept run

